### ISSUE TITLE
Ability to get the Unicode code-point

### ISSUE THREAD

**Issue by c3r38r170** [TOMIVERGARA/vscode-fontawesome-gallery#2]
Hello!
Very good job on this extension, very useful.
However, I am used to work with the Unicode number of the icons for things like custom CSS rules, IDE's text fields and such.
I don't think it would be difficult to implement a way to copy the code and even maybe the glyph (for example, in a context menu).
This idea is based on the availability of this options in [Font Awesome's website](https://fontawesome.com/v5.15/icons/500px) (see how you can copy the icon name, Unicode glyph, Unicode code-point, and HTML by clicking on the respective strings).
I can try to develop it if you let me, even if I'm not fluent in VSCode's API and Typescript, I would like to try!
If this gets done, this extension would be perfect for me, and I'm sure it would be of great value for the rest of the community too (I haven't found any similar extension, and I've been looking for days.).
Thank you very much for this extension and your time.

**Comment by TOMIVERGARA** [comment]
Hi! 
I'm happy to hear you like the extension.
I've just deployed and update with an implementation of this feature, you can find it in the VS Code Marketplace or the releases tab. You can now use the command pallete to change between the class name or the Unicode code-point as the label, if you want you can configure a key binding to make the switching faster. Hope you like it.
Thanks for your feedback!
